// Cities where DwellDash operates
export const CITIES = [
  'Delhi',
  'Mumbai', 
  'Bangalore',
  'Chennai',
  'Pune',
  'Hyderabad',
  'Kolkata',
  'Ahmedabad',
  'Jaipur',
  'Surat',
  'Lucknow',
  'Kanpur',
  'Nagpur',
  'Indore',
  'Thane',
  'Bhopal',
  'Visakhapatnam',
  'Patna',
  'Vadodara',
  'Ghaziabad',
  'Ludhiana',
  'Agra',
  'Nashik',
  'Faridabad',
  'Meerut',
  'Rajkot',
  'Kalyan-Dombivali',
  'Vasai-Virar',
  'Varanasi',
  'Srinagar',
  'Aurangabad',
  'Dhanbad',
  'Amritsar',
  'Navi Mumbai',
  'Allahabad',
  'Howrah',
  'Gwalior',
  'Jabalpur',
  'Coimbatore',
  'Vijayawada',
  'Jodhpur',
  'Madurai',
  'Raipur',
  'Kota',
  'Chandigarh',
  'Guwahati',
  'Solapur',
  'Hubli-Dharwad',
  'Tiruchirappalli',
  'Bareilly',
  'Mysore',
  'Tiruppur',
  'Gurgaon',
  'Aligarh',
  'Jalandhar',
  'Bhubaneswar',
  'Salem',
  'Warangal',
  'Guntur',
  'Bhiwandi',
  'Saharanpur',
  'Gorakhpur',
  'Bikaner',
  'Amravati',
  'Noida',
  'Jamshedpur',
  'Bhilai Nagar',
  'Cuttack',
  'Firozabad',
  'Kochi',
  'Nellore',
  'Bhavnagar',
  'Dehradun',
  'Durgapur',
  'Asansol',
  'Rourkela',
  'Nanded',
  'Kolhapur',
  'Ajmer',
  'Akola',
  'Gulbarga',
  'Jamnagar',
  'Ujjain',
  'Loni',
  'Siliguri',
  'Jhansi',
  'Ulhasnagar',
  'Jammu',
  'Sangli-Miraj & Kupwad',
  'Mangalore',
  'Erode',
  'Belgaum',
  'Ambattur',
  'Tirunelveli',
  'Malegaon',
  'Gaya',
  'Jalgaon',
  'Udaipur',
  'Maheshtala'
].sort()

// Property types available
export const PROPERTY_TYPES = [
  { value: 'single-room', label: 'Single Room' },
  { value: 'shared-room', label: 'Shared Room' },
  { value: 'flat', label: 'Flat' },
  { value: 'hostel', label: 'Hostel' }
]

// Gender preferences
export const GENDER_PREFERENCES = [
  { value: 'male', label: 'Male Only' },
  { value: 'female', label: 'Female Only' },
  { value: 'any', label: 'Co-living (Any)' }
]

// Available amenities
export const AMENITIES = [
  'wifi',
  'ac',
  'meals',
  'laundry',
  'parking',
  'security',
  'gym',
  'swimming-pool',
  'power-backup',
  'shuttle',
  'housekeeping',
  'study-area',
  'cctv',
  'biometric'
]

// Popular cities (subset of CITIES for featured listings)
export const POPULAR_CITIES = [
  'Delhi',
  'Mumbai',
  'Bangalore',
  'Chennai',
  'Pune',
  'Hyderabad',
  'Kolkata',
  'Ahmedabad',
  'Jaipur',
  'Surat',
  'Gurgaon',
  'Noida',
  'Chandigarh',
  'Kochi',
  'Indore'
] 